services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
      - composer-cache:/.composer/cache
      - npm-cache:/.npm
    depends_on:
      database:
        condition: service_healthy
    user: '${USER_ID}:${GROUP_ID}'
    networks:
      - symfony

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony

  database:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: 'db_password'
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - symfony
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "db_user", "-pdb_password"]
      timeout: 5s
      retries: 10

networks:
  symfony:

volumes:
  db-data:
  composer-cache:
  npm-cache:
